export const rooms = [
  {
    name: "Twin View Room",
    price: 560000,
    guests: 2,
    features: ["Cấm hút thuốc", "Wifi", "Máy lạnh"],
    description: "A cozy room with a beautiful view.",
    floor: 2,
    acreage: 35,
    bedType: "Twin Beds",
    maxGuests: 10,
    discount: 10,
    discountStart: "01/05/2025",
    discountEnd: "03/05/2025",
    status: "Đang bảo trì",
    images: [
      require('../assets/images/hotel1.jpg'),
      require('../assets/images/hotel2.jpg'),
      require('../assets/images/hotel3.jpg'),
    ],
  },
  {
    name: "Suite King Bed",
    price: 640000,
    guests: 2,
    features: ["Free bữa sáng", "Bồn tắm", "Wifi"],
    description: "Luxurious suite with a king bed.",
    floor: 3,
    acreage: 55,
    bedType: "King Bed",
    maxGuests: 10,
    discount: 15,
    discountStart: "05/10/2025",
    discountEnd: "15/10/2025",
    status: "Trống",
    images: [
      require('../assets/images/hotel4.jpg'),
      require('../assets/images/hotel5.jpg'),
      require('../assets/images/hotel6.jpg'),
    ],
  },
];
